# Generated by Django 4.0.3 on 2022-05-04 14:44

import Employee.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=Employee.models.upload_image_path)),
                ('phone', models.CharField(max_length=11, verbose_name='تلفن')),
                ('state', models.CharField(blank=True, choices=[('Tehran', 'تهران'), ('Shiraz', 'شیراز')], max_length=50, null=True, verbose_name='استان محل سکونت')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس')),
                ('sex', models.CharField(choices=[('Male', 'مرد'), ('Female', 'زن')], max_length=10, verbose_name='جنسیت')),
                ('marital_status', models.CharField(choices=[('Married', 'متأهل'), ('Single', 'مجرد')], max_length=10, verbose_name='وضعیت تأهل')),
                ('about_me', models.TextField(blank=True, null=True, verbose_name='درباره من')),
                ('skills', models.TextField(verbose_name='مهارت ها (مهارتهای خود را با "/ یا ،" از هم جدا کنید')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='تارخ تولد')),
                ('work_experience', models.TextField(blank=True, null=True, verbose_name='سوابق شغلی')),
                ('education', models.TextField(blank=True, null=True, verbose_name='تحصیلات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
