# Generated by Django 4.0.3 on 2022-05-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='employee_soldier_ship',
            field=models.CharField(blank=True, choices=[('A', 'کارت پایان خدمت'), ('B', 'معافیت تحصیلی'), ('C', 'معافیت دائم'), ('D', 'مشمول')], max_length=25, null=True, verbose_name='وضعیت نظام وظیفه'),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='languages',
            field=models.CharField(blank=True, choices=[('Persian', 'فارسی'), ('English', 'انگلیسی')], max_length=50, null=True, verbose_name='به چه زبان های گفتاری مسلط هستید ؟'),
        ),
    ]
