# Generated by Django 4.0.4 on 2022-05-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_remove_employeemodel_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
