# Generated by Django 4.0.3 on 2022-05-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_employeemodel_employee_soldier_ship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Married', 'متأهل'), ('Single', 'مجرد')], max_length=10, null=True, verbose_name='وضعیت تأهل'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='مهارت ها (مهارتهای خود را با "/ یا ،" از هم جدا کنید'),
        ),
    ]
