# Generated by Django 4.0.4 on 2022-05-29 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0002_remove_manager_password_company_logo_manager_about_and_more'),
        ('Employee', '0003_employeemodel_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favortes_ads', to='Employer.advertisement'),
        ),
    ]
