# Generated by Django 4.0.3 on 2022-05-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_alter_employeemodel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'مرد'), ('Female', 'زن')], max_length=10, null=True, verbose_name='جنسیت'),
        ),
    ]
