# Generated by Django 4.0.4 on 2022-06-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_alter_favorite_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='state',
            field=models.CharField(blank=True, choices=[('0', 'استان مورد نظر'), ('Tehran', 'تهران'), ('Shiraz', 'شیراز')], max_length=50, null=True, verbose_name='استان محل سکونت'),
        ),
    ]
