# Generated by Django 4.0.3 on 2022-05-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Controllers', '0002_languages'),
        ('Employee', '0004_alter_employeemodel_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='languages',
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, to='Controllers.languages'),
        ),
    ]
