# Generated by Django 4.0.4 on 2022-08-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_alter_employeemodel_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='state',
            field=models.CharField(blank=True, choices=[('0', 'استان مورد نظر'), ('Tehran', 'تهران'), ('Shiraz', 'شیراز'), ('Esfahan', 'اصفهان'), ('Mashhad', 'مشهد'), ('Tabriz', 'تبریز'), ('Hamedan', 'همدان'), ('Mazandaran', 'مازندران'), ('Gilan', 'گیلان'), ('Qom', 'قم'), ('Markazi', 'مرکزی')], max_length=50, null=True, verbose_name='استان محل سکونت'),
        ),
    ]
