# Generated by Django 4.0.4 on 2022-09-06 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0009_alter_employeemodel_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
