# Generated by Django 4.0.4 on 2022-09-09 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0010_delete_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='state',
        ),
    ]
