# Generated by Django 4.0.4 on 2022-08-14 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('icon', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MainBlogModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainBlogText', models.TextField(verbose_name='متن مقاله')),
                ('likes', models.IntegerField(verbose_name='تعداد پسندیده ها')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('enable', models.BooleanField(default=False, verbose_name='فعال')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Blog.blogcategories', verbose_name='دسته بندی')),
            ],
        ),
    ]
