# Generated by Django 4.0.4 on 2022-08-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainblogmodule',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='تعداد پسندیده ها'),
        ),
    ]
