# Generated by Django 4.0.4 on 2022-08-14 13:16

import Blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_mainblogmodule_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainblogmodule',
            name='banner',
            field=models.ImageField(upload_to=Blog.models.upload_logo_path),
        ),
    ]
