# Generated by Django 4.0.3 on 2022-05-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Controllers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_fa_type', models.CharField(max_length=30)),
                ('lang_en_type', models.CharField(max_length=30)),
            ],
        ),
    ]
