# Generated by Django 4.0.4 on 2022-06-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Controllers', '0002_languages_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='icon',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
