# Generated by Django 4.0.4 on 2022-07-28 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Controllers', '0003_categories_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
