# Generated by Django 4.0.4 on 2022-09-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Controllers', '0004_delete_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='states_iran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='نام استان')),
            ],
        ),
    ]
