# Generated by Django 4.0.3 on 2022-04-17 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Controllers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('family', models.CharField(max_length=150, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام شرکت')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('underlie', models.TextField(verbose_name='این شرکت در چه زمینه ای فعالیت میکند ؟')),
                ('valid', models.BooleanField(verbose_name='تایید کنید این شرکت وجود خارجی دارد')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان آگهی')),
                ('location', models.CharField(max_length=100, verbose_name='شهر یا استان')),
                ('text', models.TextField(verbose_name='متن آگهی')),
                ('soldier_ship', models.CharField(choices=[('passed', 'کارت پایان خدمت یا معافیت دائم'), ('temporary', 'معافیت تحصیلی'), ('other', 'مهم نیست')], max_length=25, verbose_name='وضعیت خدمت کارجو')),
                ('skills', models.TextField(verbose_name='مهارتهای مدنظر')),
                ('job_nature', models.CharField(choices=[('FullTime', 'تمام وقت'), ('PartTime', 'نیمه وقت'), ('Remote', 'دورکاری')], max_length=30, verbose_name='نوع قرارداد')),
                ('generate_in', models.DateTimeField(auto_now_add=True)),
                ('expired_in', models.DateTimeField(verbose_name='تارخ انقضای این آگهی')),
                ('salary', models.IntegerField(verbose_name='حقوق (تومان)')),
                ('expired', models.BooleanField(verbose_name='منقضی شده')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Controllers.categories', verbose_name='دسته بندی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.company', verbose_name='مربوط به شرکت')),
            ],
        ),
    ]
