# Generated by Django 4.0.3 on 2022-04-17 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='expired_in',
        ),
    ]
