# Generated by Django 4.0.4 on 2022-05-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0002_remove_manager_password_company_logo_manager_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='generate_in',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
