# Generated by Django 4.0.3 on 2022-04-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0002_remove_advertisement_expired_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='expired_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تارخ انقضای این آگهی'),
        ),
    ]
