# Generated by Django 4.0.3 on 2022-04-17 05:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0003_advertisement_expired_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='expired_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 5, 47, 29, 590042, tzinfo=utc), verbose_name='تارخ انقضای این آگهی'),
        ),
    ]
