# Generated by Django 4.0.4 on 2022-05-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0004_alter_advertisement_generate_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='generate_in',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
