# Generated by Django 4.0.3 on 2022-04-17 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0005_alter_advertisement_expired_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='category',
        ),
    ]
