# Generated by Django 4.0.4 on 2022-05-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0007_alter_advertisement_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='location',
            field=models.CharField(blank=True, choices=[('Tehran', 'تهران'), ('Shiraz', 'شیراز')], max_length=100, null=True, verbose_name='شهر یا استان'),
        ),
    ]
