# Generated by Django 4.0.3 on 2022-04-17 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0007_advertisement_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='expired',
        ),
    ]
