# Generated by Django 4.0.3 on 2022-04-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0008_remove_advertisement_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='password',
        ),
    ]
