# Generated by Django 4.0.4 on 2022-06-07 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0010_alter_hire_status_alter_hire_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='manager',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Have_companies', to='Employer.manager'),
        ),
        migrations.AlterField(
            model_name='company',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='تایید کنید این شرکت وجود خارجی دارد'),
        ),
    ]
