# Generated by Django 4.0.3 on 2022-04-19 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0011_alter_company_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employer.manager'),
        ),
        migrations.AlterField(
            model_name='company',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='تایید کنید این شرکت وجود خارجی دارد'),
        ),
    ]
