# Generated by Django 4.0.3 on 2022-04-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0013_alter_company_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='manager',
        ),
    ]
