# Generated by Django 4.0.4 on 2022-06-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0013_rename_logo_company_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='location',
            field=models.CharField(blank=True, choices=[('0', 'استان مورد نظر'), ('Tehran', 'تهران'), ('Shiraz', 'شیراز')], default='0', max_length=100, null=True, verbose_name='شهر یا استان'),
        ),
    ]
