# Generated by Django 4.0.4 on 2022-06-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0014_alter_advertisement_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='location',
            field=models.CharField(choices=[('0', 'استان مورد نظر'), ('Tehran', 'تهران'), ('Shiraz', 'شیراز')], default='0', max_length=100, verbose_name='شهر یا استان'),
        ),
    ]
