# Generated by Django 4.0.4 on 2022-06-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0015_alter_advertisement_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='About',
            field=models.TextField(default='متن معرفی کارفرما', verbose_name='درباره شما '),
        ),
    ]
