# Generated by Django 4.0.3 on 2022-04-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0016_alter_company_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='expired',
            field=models.BooleanField(default=False, verbose_name='این آگهی منقضی شده'),
        ),
    ]
