# Generated by Django 4.0.4 on 2022-06-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0017_alter_manager_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
    ]
