# Generated by Django 4.0.3 on 2022-04-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0018_alter_advertisement_expired_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='expired_in',
            field=models.DateTimeField(verbose_name='تارخ انقضای این آگهی'),
        ),
    ]
