# Generated by Django 4.0.3 on 2022-04-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0020_alter_advertisement_expired_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/png/Manager.jpg', null=True, upload_to='user/profile-pictures'),
        ),
    ]
