# Generated by Django 4.0.4 on 2022-08-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0021_alter_advertisement_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='location',
            field=models.CharField(choices=[('0', 'استان مورد نظر'), ('Tehran', 'تهران'), ('Shiraz', 'شیراز'), ('Esfahan', 'اصفهان'), ('Mashhad', 'مشهد'), ('Tabriz', 'تبریز'), ('Hamedan', 'همدان'), ('Mazandaran', 'مازندران'), ('Gilan', 'گیلان'), ('Qom', 'قم'), ('Markazi', 'مرکزی')], default='0', max_length=100, verbose_name='شهر یا استان'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='soldier_ship',
            field=models.CharField(choices=[('passed', 'کارت پایان خدمت یا معافیت دائم'), ('temporary', 'معافیت تحصیلی'), ('other', 'مهم نیست')], max_length=100, verbose_name='وضعیت خدمت کارجو'),
        ),
    ]
