# Generated by Django 4.0.3 on 2022-04-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0022_alter_manager_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='profile_pic',
            field=models.FileField(default='static/png/Manager.jpg', upload_to='user/profile-pictures'),
        ),
    ]
