# Generated by Django 4.0.4 on 2022-08-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0027_remove_hire_created_at_remove_hire_determine_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='تاریخ ارسال درخواست'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('send', 'در انتظار تأیین وضعیت'), ('seen', 'توسط کارفرما مشاهده شد'), ('accepted', 'تأیید برای مصاحبه'), ('rejected', 'رد')], default='send', max_length=15),
        ),
    ]
