# Generated by Django 4.0.3 on 2022-04-25 14:16

import Employer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0027_alter_manager_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='About',
            field=models.TextField(default='None', verbose_name='درباره شما '),
        ),
        migrations.AlterField(
            model_name='manager',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=Employer.models.upload_image_path),
        ),
    ]
