# Generated by Django 4.0.3 on 2022-04-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0028_manager_about_alter_manager_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='About',
            field=models.TextField(verbose_name='درباره شما '),
        ),
    ]
