# Generated by Django 4.0.4 on 2022-08-13 13:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0029_alter_applicant_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 13, 13, 0, 23, 987561, tzinfo=utc), verbose_name='تاریخ ارسال درخواست'),
        ),
    ]
