# Generated by Django 4.0.3 on 2022-04-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0030_remove_manager_family_remove_manager_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='family',
            field=models.CharField(default='None', max_length=150, verbose_name='نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='manager',
            name='name',
            field=models.CharField(default='None', max_length=100, verbose_name='نام'),
        ),
    ]
