# Generated by Django 4.0.4 on 2022-08-26 08:12

import Employer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0031_alter_applicant_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/images/company-2.jpg', null=True, upload_to=Employer.models.upload_image_path),
        ),
    ]
