# Generated by Django 4.0.3 on 2022-04-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0031_manager_family_manager_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='family',
            field=models.CharField(max_length=150, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
    ]
