# Generated by Django 4.0.4 on 2022-08-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0032_alter_manager_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enable', models.BooleanField(default=True, verbose_name='توسط مدیر دیده شود')),
                ('user', models.ManyToManyField(to='Employer.manager', verbose_name='مدیر مورد نظر')),
            ],
        ),
    ]
