# Generated by Django 4.0.3 on 2022-04-28 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0033_alter_advertisement_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='Employer.company', verbose_name='مربوط به شرکت'),
        ),
    ]
