# Generated by Django 4.0.4 on 2022-09-06 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0010_delete_favorite'),
        ('Employer', '0035_remove_applicant_user_applicant_employee_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='Employer.advertisement'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='employee',
            field=models.ForeignKey(blank=True, default='sss', null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.employeemodel'),
        ),
    ]
