# Generated by Django 4.0.3 on 2022-05-11 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Controllers', '0003_tags'),
        ('Employer', '0037_applicant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='advertisiment', to='Controllers.categories', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('send', 'در انتظار تأیین وضعیت'), ('seen', 'توسط کارفرما مشاهده شد'), ('accepted', 'تأیید برای مساحبه'), ('rejected', 'رد شده')], default='send', max_length=15),
        ),
    ]
