# Generated by Django 4.0.4 on 2022-09-06 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0010_delete_favorite'),
        ('Employer', '0037_alter_applicant_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='ad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='Employer.advertisement'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Employee.employeemodel'),
        ),
    ]
