# Generated by Django 4.0.3 on 2022-05-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0038_alter_advertisement_category_alter_applicant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='generate_in',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
