# Generated by Django 4.0.4 on 2022-09-09 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Controllers', '0005_states_iran'),
        ('Employer', '0038_alter_applicant_ad_alter_applicant_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Controllers.states_iran', verbose_name='شهر یا استان'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('send', 'در انتظار تأیین وضعیت'), ('seen', 'توسط کارفرما مشاهده شد'), ('accepted', 'تأیید برای مصاحبه'), ('rejected', 'ردشده')], default='send', max_length=15),
        ),
    ]
