# Generated by Django 4.0.4 on 2022-09-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0039_alter_advertisement_location_alter_applicant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='عنوان آگهی'),
        ),
    ]
