# Generated by Django 4.0.3 on 2022-05-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0040_remove_advertisement_expired_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='expired_in',
            field=models.DateField(null=True, verbose_name='تارخ انقضای این آگهی'),
        ),
    ]
