# Generated by Django 4.0.3 on 2022-05-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0042_remove_advertisement_expired_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='expired_in',
            field=models.DateTimeField(null=True, verbose_name='تارخ انقضای این آگهی'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='generate_in',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
