# Generated by Django 4.0.3 on 2022-05-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0043_advertisement_expired_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='expired_in',
            field=models.DateField(null=True, verbose_name='تارخ انقضای این آگهی'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='generate_in',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
