# Generated by Django 4.0.3 on 2022-05-14 08:49

import Employer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0048_alter_advertisement_expired_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=Employer.models.upload_logo_path),
        ),
    ]
