# Generated by Django 4.0.3 on 2022-05-24 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0049_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('send', 'در انتظار تأیین وضعیت'), ('seen', 'توسط کارفرما مشاهده شد'), ('accepted', 'تأیید برای مصاحبه'), ('rejected', 'رد شده')], default='send', max_length=15),
        ),
        migrations.AlterField(
            model_name='company',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Have_companies', to='Employer.manager'),
        ),
    ]
