# Generated by Django 4.0.4 on 2022-06-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='logo',
            field=models.CharField(max_length=30, verbose_name='لوگو'),
        ),
    ]
