# Generated by Django 4.0.4 on 2022-06-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_settings', '0003_footer_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('link', models.URLField(max_length=350, verbose_name='لینک')),
                ('icon', models.CharField(max_length=80, verbose_name='آیکون')),
            ],
        ),
    ]
