# Generated by Django 4.0.4 on 2022-06-15 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site_settings', '0004_sociallinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallinks',
            name='icon',
        ),
    ]
