# Generated by Django 4.0.4 on 2022-06-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_settings', '0006_alter_sociallinks_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='logo',
            new_name='logo_fa',
        ),
        migrations.AddField(
            model_name='footer',
            name='logo_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='لوگو'),
        ),
    ]
