# Generated by Django 4.0.4 on 2022-06-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_settings', '0007_rename_logo_footer_logo_fa_footer_logo_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='logo_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='لوگو به انگلیسی'),
        ),
    ]
